# Generated by Django 5.1.6 on 2025-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('intake', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('accepted_lt', models.CharField(max_length=255)),
                ('lt_score', models.FloatField()),
                ('min_marks', models.FloatField()),
                ('min_CGPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('system_of_study', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('intake', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('lang_test', models.CharField(max_length=50)),
                ('test_score', models.FloatField()),
                ('marks_10th', models.FloatField()),
                ('marks_12th', models.FloatField()),
                ('CGPA', models.FloatField()),
            ],
        ),
    ]
