# Generated by Django 5.1.6 on 2025-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unishortlist', '0002_university_system_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='fees',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
